wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    framework: huggingface
    huggingface_version: 4.20.1
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.7.16
    start_time: 1740065491
    t:
      1:
      - 1
      - 5
      - 11
      - 14
      - 33
      - 41
      - 49
      - 53
      - 55
      - 63
      3:
      - 13
      - 16
      4: 3.7.16
      5: 0.12.21
      6: 4.20.1
      8:
      - 2
      - 5
attn_type:
  desc: null
  value: kep_svgp
backbone:
  desc: null
  value: transformer
batch_size:
  desc: null
  value: 32
beta1:
  desc: null
  value: 0.9
beta2:
  desc: null
  value: 0.999
clip:
  desc: null
  value: 0.1
dataset:
  desc: null
  value: cola
depth:
  desc: null
  value: 2
ema_decay:
  desc: null
  value: 0.995
emb_dim:
  desc: null
  value: 128
eta_kl:
  desc: null
  value: 1.0
eta_ksvd:
  desc: null
  value: 1.0
gpu:
  desc: null
  value: '0'
hdim:
  desc: null
  value: 256
ksvd_layers:
  desc: null
  value: 2
lambda_ce:
  desc: null
  value: 1.0
lambda_mean:
  desc: null
  value: 0
lambda_var:
  desc: null
  value: 0
low_rank:
  desc: null
  value: 5
lr:
  desc: null
  value: 0.0001
max_len:
  desc: null
  value: 100
min_lr:
  desc: null
  value: 1.0e-05
min_word_count:
  desc: null
  value: 0
mlp_dropout:
  desc: null
  value: 0.0
mlp_gamma:
  desc: null
  value: 1.0
mlp_hdim1:
  desc: null
  value: 64
mlp_hdim2:
  desc: null
  value: 64
mlp_hdim3:
  desc: null
  value: 64
mlp_hdim4:
  desc: null
  value: 64
model:
  desc: null
  value: diffusion
nb_epochs:
  desc: null
  value: 50
nb_run:
  desc: null
  value: 1
nb_worker:
  desc: null
  value: 4
num_classes:
  desc: null
  value: 2
num_heads:
  desc: null
  value: 4
pretrained_dir:
  desc: null
  value: ./results/vit_out_sum
pretrained_seed:
  desc: null
  value: 1
rank_multi:
  desc: null
  value: 2
save_dir:
  desc: null
  value: ./results/diffusion
seed:
  desc: null
  value: 1
start_ema_step:
  desc: null
  value: 50
trans_depth:
  desc: null
  value: 1
trans_dropout:
  desc: null
  value: 0.1
trans_mlp_ratio:
  desc: null
  value: 1.0
trans_num_heads:
  desc: null
  value: 4
update_ema_interval:
  desc: null
  value: 5
use_ema:
  desc: null
  value: true
warmup_epoch:
  desc: null
  value: 5
weight_decay:
  desc: null
  value: 5.0e-05
