# change lr
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 torchrun --nproc_per_node=8 main.py --model diffusion_text --seed 0 --depth 24 --attn-type softmax --num_heads 14 --hdim 896 --batch-size 128 --nb-epochs 20 --nb-run 1 --lr 1e-5 --weight-decay 5e-5 --warmup-epoch 5 --save-dir ./results/diffusion --backbone transformer --pretrained_dir /home/cuong/qwen-sst/TransDiff/qwen_sst2_finetuned_merged --pretrained_seed 0 --trans_depth 4 --trans_num_heads 14 --trans_mlp_ratio 4.0 --trans_dropout 0.1 --lambda_mean 1 --lambda_var 1 --lambda_ce 1 --last_layers 5 --run_name DiT-5-seed CoLA
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 torchrun --nproc_per_node=8 main.py --model diffusion_text --seed 0 --depth 24 --attn-type softmax --num_heads 14 --hdim 896 --batch-size 128 --nb-epochs 20 --nb-run 1 --lr 3e-5 --weight-decay 5e-5 --warmup-epoch 5 --save-dir ./results/diffusion --backbone transformer --pretrained_dir /home/cuong/qwen-sst/TransDiff/qwen_sst2_finetuned_merged --pretrained_seed 0 --trans_depth 4 --trans_num_heads 14 --trans_mlp_ratio 4.0 --trans_dropout 0.1 --lambda_mean 1 --lambda_var 1 --lambda_ce 1 --last_layers 5 --run_name DiT-5-seed CoLA
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 torchrun --nproc_per_node=8 main.py --model diffusion_text --seed 0 --depth 24 --attn-type softmax --num_heads 14 --hdim 896 --batch-size 128 --nb-epochs 20 --nb-run 1 --lr 1e-4 --weight-decay 5e-5 --warmup-epoch 5 --save-dir ./results/diffusion --backbone transformer --pretrained_dir /home/cuong/qwen-sst/TransDiff/qwen_sst2_finetuned_merged --pretrained_seed 0 --trans_depth 4 --trans_num_heads 14 --trans_mlp_ratio 4.0 --trans_dropout 0.1 --lambda_mean 1 --lambda_var 1 --lambda_ce 1 --last_layers 5 --run_name DiT-5-seed CoLA
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 torchrun --nproc_per_node=8 main.py --model diffusion_text --seed 0 --depth 24 --attn-type softmax --num_heads 14 --hdim 896 --batch-size 128 --nb-epochs 20 --nb-run 1 --lr 3e-4 --weight-decay 5e-5 --warmup-epoch 5 --save-dir ./results/diffusion --backbone transformer --pretrained_dir /home/cuong/qwen-sst/TransDiff/qwen_sst2_finetuned_merged --pretrained_seed 0 --trans_depth 4 --trans_num_heads 14 --trans_mlp_ratio 4.0 --trans_dropout 0.1 --lambda_mean 1 --lambda_var 1 --lambda_ce 1 --last_layers 5 --run_name DiT-5-seed CoLA
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 torchrun --nproc_per_node=8 main.py --model diffusion_text --seed 0 --depth 24 --attn-type softmax --num_heads 14 --hdim 896 --batch-size 128 --nb-epochs 20 --nb-run 1 --lr 1e-3 --weight-decay 5e-5 --warmup-epoch 5 --save-dir ./results/diffusion --backbone transformer --pretrained_dir /home/cuong/qwen-sst/TransDiff/qwen_sst2_finetuned_merged --pretrained_seed 0 --trans_depth 4 --trans_num_heads 14 --trans_mlp_ratio 4.0 --trans_dropout 0.1 --lambda_mean 1 --lambda_var 1 --lambda_ce 1 --last_layers 5 --run_name DiT-5-seed CoLA
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 torchrun --nproc_per_node=8 main.py --model diffusion_text --seed 0 --depth 24 --attn-type softmax --num_heads 14 --hdim 896 --batch-size 128 --nb-epochs 20 --nb-run 1 --lr 3e-3 --weight-decay 5e-5 --warmup-epoch 5 --save-dir ./results/diffusion --backbone transformer --pretrained_dir /home/cuong/qwen-sst/TransDiff/qwen_sst2_finetuned_merged --pretrained_seed 0 --trans_depth 4 --trans_num_heads 14 --trans_mlp_ratio 4.0 --trans_dropout 0.1 --lambda_mean 1 --lambda_var 1 --lambda_ce 1 --last_layers 5 --run_name DiT-5-seed CoLA
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 torchrun --nproc_per_node=8 main.py --model diffusion_text --seed 0 --depth 24 --attn-type softmax --num_heads 14 --hdim 896 --batch-size 128 --nb-epochs 20 --nb-run 1 --lr 1e-2 --weight-decay 5e-5 --warmup-epoch 5 --save-dir ./results/diffusion --backbone transformer --pretrained_dir /home/cuong/qwen-sst/TransDiff/qwen_sst2_finetuned_merged --pretrained_seed 0 --trans_depth 4 --trans_num_heads 14 --trans_mlp_ratio 4.0 --trans_dropout 0.1 --lambda_mean 1 --lambda_var 1 --lambda_ce 1 --last_layers 5 --run_name DiT-5-seed CoLA
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 torchrun --nproc_per_node=8 main.py --model diffusion_text --seed 0 --depth 24 --attn-type softmax --num_heads 14 --hdim 896 --batch-size 128 --nb-epochs 20 --nb-run 1 --lr 3e-2 --weight-decay 5e-5 --warmup-epoch 5 --save-dir ./results/diffusion --backbone transformer --pretrained_dir /home/cuong/qwen-sst/TransDiff/qwen_sst2_finetuned_merged --pretrained_seed 0 --trans_depth 4 --trans_num_heads 14 --trans_mlp_ratio 4.0 --trans_dropout 0.1 --lambda_mean 1 --lambda_var 1 --lambda_ce 1 --last_layers 5 --run_name DiT-5-seed CoLA


# change last layers
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 torchrun --nproc_per_node=8 main.py --model diffusion_text --seed 0 --depth 24 --attn-type softmax --num_heads 14 --hdim 896 --batch-size 128 --nb-epochs 20 --nb-run 1 --lr 1e-4 --weight-decay 5e-5 --warmup-epoch 5 --save-dir ./results/diffusion --backbone transformer --pretrained_dir /home/cuong/qwen-sst/TransDiff/qwen_sst2_finetuned_merged --pretrained_seed 0 --trans_depth 4 --trans_num_heads 14 --trans_mlp_ratio 4.0 --trans_dropout 0.1 --lambda_mean 1 --lambda_var 1 --lambda_ce 1 --last_layers 5 --run_name DiT-5-seed CoLA
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 torchrun --nproc_per_node=8 main.py --model diffusion_text --seed 0 --depth 24 --attn-type softmax --num_heads 14 --hdim 896 --batch-size 128 --nb-epochs 20 --nb-run 1 --lr 1e-4 --weight-decay 5e-5 --warmup-epoch 5 --save-dir ./results/diffusion --backbone transformer --pretrained_dir /home/cuong/qwen-sst/TransDiff/qwen_sst2_finetuned_merged --pretrained_seed 0 --trans_depth 4 --trans_num_heads 14 --trans_mlp_ratio 4.0 --trans_dropout 0.1 --lambda_mean 1 --lambda_var 1 --lambda_ce 1 --last_layers 4 --run_name DiT-5-seed CoLA
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 torchrun --nproc_per_node=8 main.py --model diffusion_text --seed 0 --depth 24 --attn-type softmax --num_heads 14 --hdim 896 --batch-size 128 --nb-epochs 20 --nb-run 1 --lr 1e-4 --weight-decay 5e-5 --warmup-epoch 5 --save-dir ./results/diffusion --backbone transformer --pretrained_dir /home/cuong/qwen-sst/TransDiff/qwen_sst2_finetuned_merged --pretrained_seed 0 --trans_depth 4 --trans_num_heads 14 --trans_mlp_ratio 4.0 --trans_dropout 0.1 --lambda_mean 1 --lambda_var 1 --lambda_ce 1 --last_layers 3 --run_name DiT-5-seed CoLA
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 torchrun --nproc_per_node=8 main.py --model diffusion_text --seed 0 --depth 24 --attn-type softmax --num_heads 14 --hdim 896 --batch-size 128 --nb-epochs 20 --nb-run 1 --lr 1e-4 --weight-decay 5e-5 --warmup-epoch 5 --save-dir ./results/diffusion --backbone transformer --pretrained_dir /home/cuong/qwen-sst/TransDiff/qwen_sst2_finetuned_merged --pretrained_seed 0 --trans_depth 4 --trans_num_heads 14 --trans_mlp_ratio 4.0 --trans_dropout 0.1 --lambda_mean 1 --lambda_var 1 --lambda_ce 1 --last_layers 6 --run_name DiT-5-seed CoLA
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 torchrun --nproc_per_node=8 main.py --model diffusion_text --seed 0 --depth 24 --attn-type softmax --num_heads 14 --hdim 896 --batch-size 128 --nb-epochs 20 --nb-run 1 --lr 1e-4 --weight-decay 5e-5 --warmup-epoch 5 --save-dir ./results/diffusion --backbone transformer --pretrained_dir /home/cuong/qwen-sst/TransDiff/qwen_sst2_finetuned_merged --pretrained_seed 0 --trans_depth 4 --trans_num_heads 14 --trans_mlp_ratio 4.0 --trans_dropout 0.1 --lambda_mean 1 --lambda_var 1 --lambda_ce 1 --last_layers 7 --run_name DiT-5-seed CoLA
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 torchrun --nproc_per_node=8 main.py --model diffusion_text --seed 0 --depth 24 --attn-type softmax --num_heads 14 --hdim 896 --batch-size 128 --nb-epochs 20 --nb-run 1 --lr 1e-4 --weight-decay 5e-5 --warmup-epoch 5 --save-dir ./results/diffusion --backbone transformer --pretrained_dir /home/cuong/qwen-sst/TransDiff/qwen_sst2_finetuned_merged --pretrained_seed 0 --trans_depth 4 --trans_num_heads 14 --trans_mlp_ratio 4.0 --trans_dropout 0.1 --lambda_mean 1 --lambda_var 1 --lambda_ce 1 --last_layers 8 --run_name DiT-5-seed CoLA
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 torchrun --nproc_per_node=8 main.py --model diffusion_text --seed 0 --depth 24 --attn-type softmax --num_heads 14 --hdim 896 --batch-size 128 --nb-epochs 20 --nb-run 1 --lr 1e-4 --weight-decay 5e-5 --warmup-epoch 5 --save-dir ./results/diffusion --backbone transformer --pretrained_dir /home/cuong/qwen-sst/TransDiff/qwen_sst2_finetuned_merged --pretrained_seed 0 --trans_depth 4 --trans_num_heads 14 --trans_mlp_ratio 4.0 --trans_dropout 0.1 --lambda_mean 1 --lambda_var 1 --lambda_ce 1 --last_layers 9 --run_name DiT-5-seed CoLA

# # 
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 torchrun --nproc_per_node=8 main.py --model diffusion_text --seed 0 --depth 24 --attn-type softmax --num_heads 14 --hdim 896 --batch-size 128 --nb-epochs 20 --nb-run 1 --lr 1e-4 --weight-decay 5e-5 --warmup-epoch 5 --save-dir ./results/diffusion --backbone transformer --pretrained_dir /home/cuong/qwen-sst/TransDiff/qwen_sst2_finetuned_merged --pretrained_seed 0 --trans_depth 4 --trans_num_heads 14 --trans_mlp_ratio 4.0 --trans_dropout 0.1 --lambda_mean 1 --lambda_var 1 --lambda_ce 1 --last_layers 3 --run_name DiT-5-seed --epochs_stage1 10 --lr2 1e-4 --warmup-epoch2 5 CoLA
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 torchrun --nproc_per_node=8 main.py --model diffusion_text --seed 0 --depth 24 --attn-type softmax --num_heads 14 --hdim 896 --batch-size 128 --nb-epochs 20 --nb-run 1 --lr 1e-4 --weight-decay 5e-5 --warmup-epoch 3 --save-dir ./results/diffusion --backbone transformer --pretrained_dir /home/cuong/qwen-sst/TransDiff/qwen_sst2_finetuned_merged --pretrained_seed 0 --trans_depth 4 --trans_num_heads 14 --trans_mlp_ratio 4.0 --trans_dropout 0.1 --lambda_mean 1 --lambda_var 1 --lambda_ce 1 --last_layers 3 --run_name DiT-5-seed --epochs_stage1 10 --lr2 1e-4 --warmup-epoch2 3 CoLA
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 torchrun --nproc_per_node=8 main.py --model diffusion_text --seed 0 --depth 24 --attn-type softmax --num_heads 14 --hdim 896 --batch-size 128 --nb-epochs 20 --nb-run 1 --lr 1e-4 --weight-decay 5e-5 --warmup-epoch 5 --save-dir ./results/diffusion --backbone transformer --pretrained_dir /home/cuong/qwen-sst/TransDiff/qwen_sst2_finetuned_merged --pretrained_seed 0 --trans_depth 4 --trans_num_heads 14 --trans_mlp_ratio 4.0 --trans_dropout 0.1 --lambda_mean 1 --lambda_var 1 --lambda_ce 1 --last_layers 5 --run_name DiT-5-seed --epochs_stage1 10 --lr2 1e-4 --warmup-epoch2 5 CoLA
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 torchrun --nproc_per_node=8 main.py --model diffusion_text --seed 0 --depth 24 --attn-type softmax --num_heads 14 --hdim 896 --batch-size 128 --nb-epochs 20 --nb-run 1 --lr 1e-4 --weight-decay 5e-5 --warmup-epoch 3 --save-dir ./results/diffusion --backbone transformer --pretrained_dir /home/cuong/qwen-sst/TransDiff/qwen_sst2_finetuned_merged --pretrained_seed 0 --trans_depth 4 --trans_num_heads 14 --trans_mlp_ratio 4.0 --trans_dropout 0.1 --lambda_mean 1 --lambda_var 1 --lambda_ce 1 --last_layers 5 --run_name DiT-5-seed --epochs_stage1 10 --lr2 1e-4 --warmup-epoch2 3 CoLA


# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 torchrun --nproc_per_node=8 main.py --model diffusion_text --seed 0 --depth 24 --attn-type softmax --num_heads 14 --hdim 896 --batch-size 128 --nb-epochs 20 --nb-run 1 --lr 5e-5 --weight-decay 5e-5 --warmup-epoch 3 --save-dir ./results/diffusion --backbone transformer --pretrained_dir /home/cuong/qwen-sst/TransDiff/qwen_sst2_finetuned_merged --pretrained_seed 0 --trans_depth 4 --trans_num_heads 14 --trans_mlp_ratio 4.0 --trans_dropout 0.1 --lambda_mean 1 --lambda_var 1 --lambda_ce 1 --last_layers 3 --run_name DiT-5-seed --epochs_stage1 10 --lr2 5e-5 --warmup-epoch2 3 --min-lr 1e-7 CoLA
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 torchrun --nproc_per_node=8 main.py --model diffusion_text --seed 0 --depth 24 --attn-type softmax --num_heads 14 --hdim 896 --batch-size 128 --nb-epochs 20 --nb-run 1 --lr 3e-5 --weight-decay 5e-5 --warmup-epoch 3 --save-dir ./results/diffusion --backbone transformer --pretrained_dir /home/cuong/qwen-sst/TransDiff/qwen_sst2_finetuned_merged --pretrained_seed 0 --trans_depth 4 --trans_num_heads 14 --trans_mlp_ratio 4.0 --trans_dropout 0.1 --lambda_mean 1 --lambda_var 1 --lambda_ce 1 --last_layers 3 --run_name DiT-5-seed --epochs_stage1 10 --lr2 3e-5 --warmup-epoch2 3 --min-lr 1e-7 CoLA
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 torchrun --nproc_per_node=8 main.py --model diffusion_text --seed 0 --depth 24 --attn-type softmax --num_heads 14 --hdim 896 --batch-size 128 --nb-epochs 20 --nb-run 1 --lr 1e-5 --weight-decay 5e-5 --warmup-epoch 3 --save-dir ./results/diffusion --backbone transformer --pretrained_dir /home/cuong/qwen-sst/TransDiff/qwen_sst2_finetuned_merged --pretrained_seed 0 --trans_depth 4 --trans_num_heads 14 --trans_mlp_ratio 4.0 --trans_dropout 0.1 --lambda_mean 1 --lambda_var 1 --lambda_ce 1 --last_layers 3 --run_name DiT-5-seed --epochs_stage1 10 --lr2 1e-5 --warmup-epoch2 3 --min-lr 1e-7 CoLA
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 torchrun --nproc_per_node=8 main.py --model diffusion_text --seed 0 --depth 24 --attn-type softmax --num_heads 14 --hdim 896 --batch-size 128 --nb-epochs 20 --nb-run 1 --lr 5e-6 --weight-decay 5e-5 --warmup-epoch 3 --save-dir ./results/diffusion --backbone transformer --pretrained_dir /home/cuong/qwen-sst/TransDiff/qwen_sst2_finetuned_merged --pretrained_seed 0 --trans_depth 4 --trans_num_heads 14 --trans_mlp_ratio 4.0 --trans_dropout 0.1 --lambda_mean 1 --lambda_var 1 --lambda_ce 1 --last_layers 3 --run_name DiT-5-seed --epochs_stage1 10 --lr2 5e-6 --warmup-epoch2 3 --min-lr 1e-7 CoLA
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 torchrun --nproc_per_node=8 main.py --model diffusion_text --seed 0 --depth 24 --attn-type softmax --num_heads 14 --hdim 896 --batch-size 128 --nb-epochs 20 --nb-run 1 --lr 3e-6 --weight-decay 5e-5 --warmup-epoch 3 --save-dir ./results/diffusion --backbone transformer --pretrained_dir /home/cuong/qwen-sst/TransDiff/qwen_sst2_finetuned_merged --pretrained_seed 0 --trans_depth 4 --trans_num_heads 14 --trans_mlp_ratio 4.0 --trans_dropout 0.1 --lambda_mean 1 --lambda_var 1 --lambda_ce 1 --last_layers 3 --run_name DiT-5-seed --epochs_stage1 10 --lr2 3e-6 --warmup-epoch2 3 --min-lr 1e-7 CoLA
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 torchrun --nproc_per_node=8 main.py --model diffusion_text --seed 0 --depth 24 --attn-type softmax --num_heads 14 --hdim 896 --batch-size 128 --nb-epochs 20 --nb-run 1 --lr 1e-6 --weight-decay 5e-5 --warmup-epoch 3 --save-dir ./results/diffusion --backbone transformer --pretrained_dir /home/cuong/qwen-sst/TransDiff/qwen_sst2_finetuned_merged --pretrained_seed 0 --trans_depth 4 --trans_num_heads 14 --trans_mlp_ratio 4.0 --trans_dropout 0.1 --lambda_mean 1 --lambda_var 1 --lambda_ce 1 --last_layers 3 --run_name DiT-5-seed --epochs_stage1 10 --lr2 1e-6 --warmup-epoch2 3 --min-lr 1e-7 CoLA

# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 torchrun --nproc_per_node=8 main.py --model diffusion_text --seed 0 --depth 24 --attn-type softmax --num_heads 14 --hdim 896 --batch-size 128 --nb-epochs 20 --nb-run 1 --lr 5e-5 --weight-decay 5e-5 --warmup-epoch 3 --save-dir ./results/diffusion --backbone transformer --pretrained_dir /home/cuong/qwen-sst/TransDiff/qwen_sst2_finetuned_merged --pretrained_seed 0 --trans_depth 4 --trans_num_heads 14 --trans_mlp_ratio 4.0 --trans_dropout 0.1 --lambda_mean 1 --lambda_var 1 --lambda_ce 1 --last_layers 7 --run_name DiT-5-seed --epochs_stage1 10 --lr2 5e-5 --warmup-epoch2 3 --min-lr 1e-7 CoLA
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 torchrun --nproc_per_node=8 main.py --model diffusion_text --seed 0 --depth 24 --attn-type softmax --num_heads 14 --hdim 896 --batch-size 128 --nb-epochs 20 --nb-run 1 --lr 5e-5 --weight-decay 5e-5 --warmup-epoch 3 --save-dir ./results/diffusion --backbone transformer --pretrained_dir /home/cuong/qwen-sst/TransDiff/qwen_sst2_finetuned_merged --pretrained_seed 0 --trans_depth 4 --trans_num_heads 14 --trans_mlp_ratio 4.0 --trans_dropout 0.1 --lambda_mean 1 --lambda_var 1 --lambda_ce 1 --last_layers 8 --run_name DiT-5-seed --epochs_stage1 10 --lr2 5e-5 --warmup-epoch2 3 --min-lr 1e-7 CoLA
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 torchrun --nproc_per_node=8 main.py --model diffusion_text --seed 0 --depth 24 --attn-type softmax --num_heads 14 --hdim 896 --batch-size 128 --nb-epochs 20 --nb-run 1 --lr 5e-5 --weight-decay 5e-5 --warmup-epoch 3 --save-dir ./results/diffusion --backbone transformer --pretrained_dir /home/cuong/qwen-sst/TransDiff/qwen_sst2_finetuned_merged --pretrained_seed 0 --trans_depth 4 --trans_num_heads 14 --trans_mlp_ratio 4.0 --trans_dropout 0.1 --lambda_mean 1 --lambda_var 1 --lambda_ce 1 --last_layers 9 --run_name DiT-5-seed --epochs_stage1 10 --lr2 5e-5 --warmup-epoch2 3 --min-lr 1e-7 CoLA
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 torchrun --nproc_per_node=8 main.py --model diffusion_text --seed 0 --depth 24 --attn-type softmax --num_heads 14 --hdim 896 --batch-size 128 --nb-epochs 20 --nb-run 1 --lr 5e-5 --weight-decay 5e-5 --warmup-epoch 3 --save-dir ./results/diffusion --backbone transformer --pretrained_dir /home/cuong/qwen-sst/TransDiff/qwen_sst2_finetuned_merged --pretrained_seed 0 --trans_depth 4 --trans_num_heads 14 --trans_mlp_ratio 4.0 --trans_dropout 0.1 --lambda_mean 1 --lambda_var 1 --lambda_ce 1 --last_layers 10 --run_name DiT-5-seed --epochs_stage1 10 --lr2 5e-5 --warmup-epoch2 3 --min-lr 1e-7 CoLA
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 torchrun --nproc_per_node=8 main.py --model diffusion_text --seed 0 --depth 24 --attn-type softmax --num_heads 14 --hdim 896 --batch-size 128 --nb-epochs 20 --nb-run 1 --lr 5e-5 --weight-decay 5e-5 --warmup-epoch 3 --save-dir ./results/diffusion --backbone transformer --pretrained_dir /home/cuong/qwen-sst/TransDiff/qwen_sst2_finetuned_merged --pretrained_seed 0 --trans_depth 4 --trans_num_heads 14 --trans_mlp_ratio 4.0 --trans_dropout 0.1 --lambda_mean 1 --lambda_var 1 --lambda_ce 1 --last_layers 11 --run_name DiT-5-seed --epochs_stage1 10 --lr2 5e-5 --warmup-epoch2 3 --min-lr 1e-7 CoLA
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 torchrun --nproc_per_node=8 main.py --model diffusion_text --seed 0 --depth 24 --attn-type softmax --num_heads 14 --hdim 896 --batch-size 128 --nb-epochs 20 --nb-run 1 --lr 5e-5 --weight-decay 5e-5 --warmup-epoch 3 --save-dir ./results/diffusion --backbone transformer --pretrained_dir /home/cuong/qwen-sst/TransDiff/qwen_sst2_finetuned_merged --pretrained_seed 0 --trans_depth 4 --trans_num_heads 14 --trans_mlp_ratio 4.0 --trans_dropout 0.1 --lambda_mean 1 --lambda_var 1 --lambda_ce 1 --last_layers 12 --run_name DiT-5-seed --epochs_stage1 10 --lr2 5e-5 --warmup-epoch2 3 --min-lr 1e-7 CoLA

# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 torchrun --nproc_per_node=8 main.py --model diffusion_text --seed 0 --depth 24 --attn-type softmax --num_heads 14 --hdim 896 --batch-size 128 --nb-epochs 20 --nb-run 1 --lr 5e-5 --weight-decay 5e-7 --warmup-epoch 3 --save-dir ./results/diffusion --backbone transformer --pretrained_dir /home/cuong/qwen-sst/TransDiff/qwen_sst2_finetuned_merged --pretrained_seed 0 --trans_depth 4 --trans_num_heads 14 --trans_mlp_ratio 4.0 --trans_dropout 0.1 --lambda_mean 1 --lambda_var 1 --lambda_ce 1 --last_layers 3 --run_name DiT-5-seed --epochs_stage1 10 --lr2 5e-5 --warmup-epoch2 3 --min-lr 1e-7 CoLA
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 torchrun --nproc_per_node=8 main.py --model diffusion_text --seed 0 --depth 24 --attn-type softmax --num_heads 14 --hdim 896 --batch-size 128 --nb-epochs 20 --nb-run 1 --lr 5e-5 --weight-decay 5e-7 --warmup-epoch 3 --save-dir ./results/diffusion --backbone transformer --pretrained_dir /home/cuong/qwen-sst/TransDiff/qwen_sst2_finetuned_merged --pretrained_seed 0 --trans_depth 3 --trans_num_heads 14 --trans_mlp_ratio 4.0 --trans_dropout 0.1 --lambda_mean 1 --lambda_var 1 --lambda_ce 1 --last_layers 3 --run_name DiT-5-seed --epochs_stage1 10 --lr2 5e-5 --warmup-epoch2 3 --min-lr 1e-7 CoLA
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 torchrun --nproc_per_node=8 main.py --model diffusion_text --seed 0 --depth 24 --attn-type softmax --num_heads 14 --hdim 896 --batch-size 128 --nb-epochs 20 --nb-run 1 --lr 5e-5 --weight-decay 5e-7 --warmup-epoch 3 --save-dir ./results/diffusion --backbone transformer --pretrained_dir /home/cuong/qwen-sst/TransDiff/qwen_sst2_finetuned_merged --pretrained_seed 0 --trans_depth 2 --trans_num_heads 14 --trans_mlp_ratio 4.0 --trans_dropout 0.1 --lambda_mean 1 --lambda_var 1 --lambda_ce 1 --last_layers 3 --run_name DiT-5-seed --epochs_stage1 10 --lr2 5e-5 --warmup-epoch2 3 --min-lr 1e-7 CoLA
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 torchrun --nproc_per_node=8 main.py --model diffusion_text --seed 0 --depth 24 --attn-type softmax --num_heads 14 --hdim 896 --batch-size 128 --nb-epochs 20 --nb-run 1 --lr 5e-5 --weight-decay 5e-7 --warmup-epoch 3 --save-dir ./results/diffusion --backbone transformer --pretrained_dir /home/cuong/qwen-sst/TransDiff/qwen_sst2_finetuned_merged --pretrained_seed 0 --trans_depth 1 --trans_num_heads 14 --trans_mlp_ratio 4.0 --trans_dropout 0.1 --lambda_mean 1 --lambda_var 1 --lambda_ce 1 --last_layers 3 --run_name DiT-5-seed --epochs_stage1 10 --lr2 5e-5 --warmup-epoch2 3 --min-lr 1e-7 CoLA
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 torchrun --nproc_per_node=8 main.py --model diffusion_text --seed 0 --depth 24 --attn-type softmax --num_heads 14 --hdim 896 --batch-size 128 --nb-epochs 20 --nb-run 1 --lr 5e-5 --weight-decay 5e-7 --warmup-epoch 3 --save-dir ./results/diffusion --backbone transformer --pretrained_dir /home/cuong/qwen-sst/TransDiff/qwen_sst2_finetuned_merged --pretrained_seed 0 --trans_depth 5 --trans_num_heads 14 --trans_mlp_ratio 4.0 --trans_dropout 0.1 --lambda_mean 1 --lambda_var 1 --lambda_ce 1 --last_layers 3 --run_name DiT-5-seed --epochs_stage1 10 --lr2 5e-5 --warmup-epoch2 3 --min-lr 1e-7 CoLA
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 torchrun --nproc_per_node=8 main.py --model diffusion_text --seed 0 --depth 24 --attn-type softmax --num_heads 14 --hdim 896 --batch-size 128 --nb-epochs 20 --nb-run 1 --lr 5e-5 --weight-decay 5e-7 --warmup-epoch 3 --save-dir ./results/diffusion --backbone transformer --pretrained_dir /home/cuong/qwen-sst/TransDiff/qwen_sst2_finetuned_merged --pretrained_seed 0 --trans_depth 6 --trans_num_heads 14 --trans_mlp_ratio 4.0 --trans_dropout 0.1 --lambda_mean 1 --lambda_var 1 --lambda_ce 1 --last_layers 3 --run_name DiT-5-seed --epochs_stage1 10 --lr2 5e-5 --warmup-epoch2 3 --min-lr 1e-7 CoLA
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 torchrun --nproc_per_node=8 main.py --model diffusion_text --seed 0 --depth 24 --attn-type softmax --num_heads 14 --hdim 896 --batch-size 128 --nb-epochs 20 --nb-run 1 --lr 5e-5 --weight-decay 5e-7 --warmup-epoch 3 --save-dir ./results/diffusion --backbone transformer --pretrained_dir /home/cuong/qwen-sst/TransDiff/qwen_sst2_finetuned_merged --pretrained_seed 0 --trans_depth 7 --trans_num_heads 14 --trans_mlp_ratio 4.0 --trans_dropout 0.1 --lambda_mean 1 --lambda_var 1 --lambda_ce 1 --last_layers 3 --run_name DiT-5-seed --epochs_stage1 10 --lr2 5e-5 --warmup-epoch2 3 --min-lr 1e-7 CoLA

# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 torchrun --nproc_per_node=8 main.py --model diffusion_text --seed 0 --depth 24 --attn-type softmax --num_heads 14 --hdim 896 --batch-size 128 --nb-epochs 30 --nb-run 1 --lr 5e-5 --weight-decay 5e-7 --warmup-epoch 5 --save-dir ./results/diffusion --backbone transformer --pretrained_dir /home/cuong/qwen-sst/TransDiff/qwen_sst2_finetuned_merged --pretrained_seed 0 --trans_depth 3 --trans_num_heads 14 --trans_mlp_ratio 4.0 --trans_dropout 0.1 --lambda_mean 1 --lambda_var 1 --lambda_ce 1 --last_layers 3 --run_name DiT-5-seed --epochs_stage1 15 --lr2 5e-5 --warmup-epoch2 5 --min-lr 1e-7 CoLA
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 torchrun --nproc_per_node=8 main.py --model diffusion_text --seed 0 --depth 24 --attn-type softmax --num_heads 14 --hdim 896 --batch-size 128 --nb-epochs 40 --nb-run 1 --lr 5e-5 --weight-decay 5e-7 --warmup-epoch 5 --save-dir ./results/diffusion --backbone transformer --pretrained_dir /home/cuong/qwen-sst/TransDiff/qwen_sst2_finetuned_merged --pretrained_seed 0 --trans_depth 3 --trans_num_heads 14 --trans_mlp_ratio 4.0 --trans_dropout 0.1 --lambda_mean 1 --lambda_var 1 --lambda_ce 1 --last_layers 3 --run_name DiT-5-seed --epochs_stage1 20 --lr2 5e-5 --warmup-epoch2 5 --min-lr 1e-7 CoLA
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 torchrun --nproc_per_node=8 main.py --model diffusion_text --seed 0 --depth 24 --attn-type softmax --num_heads 14 --hdim 896 --batch-size 128 --nb-epochs 50 --nb-run 1 --lr 5e-5 --weight-decay 5e-7 --warmup-epoch 5 --save-dir ./results/diffusion --backbone transformer --pretrained_dir /home/cuong/qwen-sst/TransDiff/qwen_sst2_finetuned_merged --pretrained_seed 0 --trans_depth 3 --trans_num_heads 14 --trans_mlp_ratio 4.0 --trans_dropout 0.1 --lambda_mean 1 --lambda_var 1 --lambda_ce 1 --last_layers 3 --run_name DiT-5-seed --epochs_stage1 25 --lr2 5e-5 --warmup-epoch2 5 --min-lr 1e-7 CoLA


# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 torchrun --nproc_per_node=8 main.py --model diffusion_text --seed 0 --depth 24 --attn-type softmax --num_heads 14 --hdim 896 --batch-size 128 --nb-epochs 20 --nb-run 1 --lr 5e-5 --weight-decay 5e-7 --warmup-epoch 5 --save-dir ./results/diffusion --backbone transformer --pretrained_dir /home/cuong/qwen-sst/TransDiff/qwen_sst2_finetuned_merged --pretrained_seed 0 --trans_depth 3 --trans_num_heads 14 --trans_mlp_ratio 4.0 --trans_dropout 0.1 --lambda_mean 1 --lambda_var 1 --lambda_ce 1 --last_layers 3 --run_name DiT-5-seed --min-lr 1e-7 CoLA
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 torchrun --nproc_per_node=8 main.py --model diffusion_text --seed 0 --depth 24 --attn-type softmax --num_heads 14 --hdim 896 --batch-size 128 --nb-epochs 20 --nb-run 1 --lr 1e-5 --weight-decay 5e-7 --warmup-epoch 5 --save-dir ./results/diffusion --backbone transformer --pretrained_dir /home/cuong/qwen-sst/TransDiff/qwen_sst2_finetuned_merged --pretrained_seed 0 --trans_depth 3 --trans_num_heads 14 --trans_mlp_ratio 4.0 --trans_dropout 0.1 --lambda_mean 1 --lambda_var 1 --lambda_ce 1 --last_layers 3 --run_name DiT-5-seed --min-lr 1e-7 CoLA
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 torchrun --nproc_per_node=8 main.py --model diffusion_text --seed 0 --depth 24 --attn-type softmax --num_heads 14 --hdim 896 --batch-size 128 --nb-epochs 20 --nb-run 1 --lr 5e-4 --weight-decay 5e-7 --warmup-epoch 5 --save-dir ./results/diffusion --backbone transformer --pretrained_dir /home/cuong/qwen-sst/TransDiff/qwen_sst2_finetuned_merged --pretrained_seed 0 --trans_depth 3 --trans_num_heads 14 --trans_mlp_ratio 4.0 --trans_dropout 0.1 --lambda_mean 1 --lambda_var 1 --lambda_ce 1 --last_layers 3 --run_name DiT-5-seed --min-lr 1e-7 CoLA
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 torchrun --nproc_per_node=8 main.py --model diffusion_text --seed 0 --depth 24 --attn-type softmax --num_heads 14 --hdim 896 --batch-size 128 --nb-epochs 20 --nb-run 1 --lr 1e-4 --weight-decay 5e-7 --warmup-epoch 5 --save-dir ./results/diffusion --backbone transformer --pretrained_dir /home/cuong/qwen-sst/TransDiff/qwen_sst2_finetuned_merged --pretrained_seed 0 --trans_depth 3 --trans_num_heads 14 --trans_mlp_ratio 4.0 --trans_dropout 0.1 --lambda_mean 1 --lambda_var 1 --lambda_ce 1 --last_layers 3 --run_name DiT-5-seed --min-lr 1e-7 CoLA
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 torchrun --nproc_per_node=8 main.py --model diffusion_text --seed 0 --depth 24 --attn-type softmax --num_heads 14 --hdim 896 --batch-size 128 --nb-epochs 20 --nb-run 1 --lr 1e-3 --weight-decay 5e-7 --warmup-epoch 5 --save-dir ./results/diffusion --backbone transformer --pretrained_dir /home/cuong/qwen-sst/TransDiff/qwen_sst2_finetuned_merged --pretrained_seed 0 --trans_depth 3 --trans_num_heads 14 --trans_mlp_ratio 4.0 --trans_dropout 0.1 --lambda_mean 1 --lambda_var 1 --lambda_ce 1 --last_layers 3 --run_name DiT-5-seed --min-lr 1e-7 CoLA

# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 torchrun --nproc_per_node=8 main.py --model diffusion_text --seed 0 --depth 24 --attn-type softmax --num_heads 14 --hdim 896 --batch-size 128 --nb-epochs 20 --nb-run 1 --lr 5e-5 --weight-decay 5e-7 --warmup-epoch 5 --save-dir ./results/diffusion --backbone transformer --pretrained_dir /home/cuong/qwen-sst/TransDiff/qwen_sst2_finetuned_merged --pretrained_seed 0 --trans_depth 3 --trans_num_heads 14 --trans_mlp_ratio 4.0 --trans_dropout 0.1 --lambda_mean 0 --lambda_var 0 --lambda_ce 1 --last_layers 3 --run_name DiT-5-seed --min-lr 1e-7 CoLA
CUDA_VISIBLE_DEVICES=0,1,2,3 torchrun --nproc_per_node=4 main.py --model diffusion_text --seed 0 --depth 24 --attn-type softmax --num_heads 14 --hdim 896 --batch-size 128 --nb-epochs 20 --nb-run 1 --lr 5e-5 --weight-decay 5e-7 --warmup-epoch 5 --save-dir ./results/diffusion --backbone transformer --pretrained_dir /home/cuong/qwen-sst/TransDiff/qwen_sst2_finetuned_merged --pretrained_seed 0 --trans_depth 3 --trans_num_heads 14 --trans_mlp_ratio 4.0 --trans_dropout 0.1 --lambda_mean 1 --lambda_var 1 --lambda_ce 1 --last_layers 3 --run_name DiT-5-seed --min-lr 1e-7 CoLA
